title: Nhat Le # your name (or website title) here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Nhat Le. I'm currently an undergraduate student and a research assistant at California State University, Long Beach. I'm working
  on projects where I apply my knowledge about 
  <br><br>
  My main interests include machine learning, deep learning and their applications. I'm proficient in Python and C++, data visualization with Tableau, Matplotlib and Seaborn. I'm seeking a full-time or internship in software engineering. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/nl2/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
